import {
  available,
  unavailable,
  type AgentMessage,
  type KnowledgeItem,
  type Project,
  type User,
} from "./types";

export const users: User[] = [
  { id: "u1", name: "Mei Tan", initials: "MT", role: "Project Lead", org: "Automation / Litho" },
  { id: "u2", name: "Arun Prakash", initials: "AP", role: "Project Lead", org: "Automation / Etch" },
  { id: "u3", name: "Dana Reyes", initials: "DR", role: "Engineer", org: "Automation" },
  { id: "u4", name: "Kenji Watanabe", initials: "KW", role: "Engineer", org: "Automation / Metrology" },
  { id: "u5", name: "Sofia Lindqvist", initials: "SL", role: "Engineer", org: "Automation / Controls" },
  { id: "u6", name: "Tomas Nowak", initials: "TN", role: "Engineer", org: "Automation / Floor" },
  { id: "u7", name: "Priya Sharma", initials: "PS", role: "System Admin", org: "Automation / IT" },
];

export const currentUser = users[0];

export const eligibleLeads = users.filter(
  (u) => u.role === "Project Lead" || u.role === "System Admin",
);

export const projects: Project[] = [
  {
    id: "PRJ202609001",
    name: "Litho Bay AMHS Stocker Retrofit",
    building: "B2",
    area: "Litho Bay 4",
    type: "New Project",
    lead: users[0],
    stage: "In Progress",
    health: "At Risk",
    startDate: "2026-09-01",
    targetFinishDate: "2026-12-20",
    lastUpdated: "2026-09-15T08:40:00Z",
    budget: {
      currency: "USD",
      approved: 1_850_000,
      committed: 1_420_000,
      actual: 912_400,
      forecastAtCompletion: 1_968_000,
    },
    roi: {
      expectedPct: available(41.2),
      realizedPct: unavailable("Realized benefit is measured 90 days after SAT."),
      paybackMonths: available(29),
      assumptions:
        "Annualized benefit from 3.1 FTE redeployment and 4% throughput uplift; operating cost includes vendor service contract at $84k/yr.",
    },
    vendor: {
      name: "Daifuku Automation",
      health: "At Risk",
      contact: "l.ortega@daifuku.example",
      milestonesComplete: 4,
      milestonesTotal: 7,
      delivery: 72,
      quality: 88,
      responsiveness: 64,
      openActions: 3,
      lastUpdate: "2026-09-12",
    },
    risks: [
      {
        id: "R-04",
        title: "Controller firmware revision not validated against fab MES",
        severity: "Critical",
        probability: 4,
        impact: 5,
        owner: "Sofia Lindqvist",
        mitigation: "Schedule joint validation window with MES team before FAT.",
        mitigationStatus: "In progress",
      },
      {
        id: "R-07",
        title: "Long-lead rail segments slipping from vendor plant",
        severity: "High",
        probability: 3,
        impact: 4,
        owner: "Mei Tan",
        mitigation: "Dual-source remaining 40m; weekly expedite call.",
        mitigationStatus: "In progress",
      },
      {
        id: "R-11",
        title: "Bay 4 tool move conflicts with install window",
        severity: "Medium",
        probability: 3,
        impact: 3,
        owner: "Tomas Nowak",
        mitigation: "Align with fab move calendar at October gate review.",
        mitigationStatus: "Not started",
      },
    ],
    issues: [
      {
        id: "I-12",
        title: "Stocker load port alignment out of tolerance on unit 2",
        severity: "Critical",
        owner: "Kenji Watanabe",
        ageDays: 6,
        overdue: true,
      },
      {
        id: "I-15",
        title: "Vendor has not supplied updated electrical schematics",
        severity: "High",
        owner: "Mei Tan",
        ageDays: 11,
        overdue: true,
      },
      {
        id: "I-18",
        title: "Spare parts list missing manufacturer part numbers",
        severity: "Medium",
        owner: "Sofia Lindqvist",
        ageDays: 3,
        overdue: false,
      },
      {
        id: "I-19",
        title: "Training plan not yet scheduled for shift C",
        severity: "Low",
        owner: "Tomas Nowak",
        ageDays: 2,
        overdue: false,
      },
    ],
    milestones: [
      { id: "M1", name: "Requirements frozen", plannedDate: "2026-09-12", actualDate: "2026-09-11", weight: 10, complete: true },
      { id: "M2", name: "Detailed design approved", plannedDate: "2026-09-30", actualDate: "2026-10-04", weight: 20, complete: true },
      { id: "M3", name: "Factory acceptance test", plannedDate: "2026-10-28", weight: 25, complete: false },
      { id: "M4", name: "Site install complete", plannedDate: "2026-11-25", weight: 25, complete: false },
      { id: "M5", name: "SAT and buy-off", plannedDate: "2026-12-18", weight: 20, complete: false },
    ],
    benefit: {
      plannedFte: available(3.1),
      validatedFte: available(2.4),
      realizedFte: unavailable("Realized after 90-day post-SAT measurement window."),
      plannedKwh: available(412_000),
      validatedKwh: available(338_000),
      realizedKwh: unavailable("Sub-metering installed; baseline period still running."),
      measurementPeriod: "Annualized, FY27",
    },
    ai: {
      activeUsers: 9,
      prompts: 214,
      citedSearches: 168,
      draftsProposed: 31,
      actionsConfirmed: 12,
      estimatedHoursSaved: 47,
    },
    progressSeries: [
      { label: "Jul", planned: 0, actual: 0 },
      { label: "Aug", planned: 8, actual: 6 },
      { label: "Sep", planned: 26, actual: 21 },
      { label: "Oct", planned: 52, actual: null },
      { label: "Nov", planned: 78, actual: null },
      { label: "Dec", planned: 100, actual: null },
    ],
  },
  {
    id: "CIP202609002",
    name: "Etch Chamber Clean Cycle Optimization",
    building: "B1",
    area: "Etch Bay 2",
    type: "CIP",
    lead: users[1],
    stage: "FAT",
    health: "On Track",
    startDate: "2026-09-08",
    targetFinishDate: "2026-11-14",
    lastUpdated: "2026-09-15T06:15:00Z",
    budget: {
      currency: "USD",
      approved: 320_000,
      committed: 268_000,
      actual: 201_500,
      forecastAtCompletion: 309_000,
    },
    roi: {
      expectedPct: available(88.5),
      realizedPct: available(61.0),
      paybackMonths: available(13),
      assumptions:
        "Benefit from 11% clean-cycle time reduction across 6 chambers; excludes consumable price volatility.",
    },
    vendor: {
      name: "Lam Research Services",
      health: "On Track",
      contact: "services@lamresearch.example",
      milestonesComplete: 5,
      milestonesTotal: 6,
      delivery: 94,
      quality: 91,
      responsiveness: 89,
      openActions: 1,
      lastUpdate: "2026-09-14",
    },
    risks: [
      {
        id: "R-02",
        title: "Recipe change requires requalification on two chambers",
        severity: "Medium",
        probability: 3,
        impact: 3,
        owner: "Arun Prakash",
        mitigation: "Requal slots booked for week 42.",
        mitigationStatus: "In progress",
      },
    ],
    issues: [
      {
        id: "I-07",
        title: "Data logger dropout during overnight runs",
        severity: "Medium",
        owner: "Kenji Watanabe",
        ageDays: 4,
        overdue: false,
      },
    ],
    milestones: [
      { id: "M1", name: "Baseline data collected", plannedDate: "2026-09-18", actualDate: "2026-09-16", weight: 20, complete: true },
      { id: "M2", name: "Recipe candidates screened", plannedDate: "2026-10-02", actualDate: "2026-10-01", weight: 25, complete: true },
      { id: "M3", name: "FAT on pilot chamber", plannedDate: "2026-10-20", weight: 25, complete: false },
      { id: "M4", name: "Fleet rollout and buy-off", plannedDate: "2026-11-12", weight: 30, complete: false },
    ],
    benefit: {
      plannedFte: available(0.8),
      validatedFte: available(0.8),
      realizedFte: available(0.5),
      plannedKwh: available(1_240_000),
      validatedKwh: available(1_180_000),
      realizedKwh: available(690_000),
      measurementPeriod: "Annualized, FY27",
    },
    ai: {
      activeUsers: 6,
      prompts: 143,
      citedSearches: 121,
      draftsProposed: 18,
      actionsConfirmed: 9,
      estimatedHoursSaved: 33,
    },
    progressSeries: [
      { label: "Jul", planned: 0, actual: 0 },
      { label: "Aug", planned: 12, actual: 14 },
      { label: "Sep", planned: 38, actual: 41 },
      { label: "Oct", planned: 70, actual: null },
      { label: "Nov", planned: 100, actual: null },
      { label: "Dec", planned: 100, actual: null },
    ],
  },
  {
    id: "PRJ202608004",
    name: "Metrology Data Pipeline Consolidation",
    building: "B3",
    area: "Metrology Lab",
    type: "New Project",
    lead: users[0],
    stage: "Planned",
    health: "On Track",
    startDate: "2026-10-01",
    targetFinishDate: "2027-03-31",
    lastUpdated: "2026-09-14T15:02:00Z",
    budget: {
      currency: "USD",
      approved: 640_000,
      committed: 90_000,
      actual: 18_200,
      forecastAtCompletion: 631_000,
    },
    roi: {
      expectedPct: unavailable("Benefit model pending manager validation."),
      realizedPct: unavailable("Project has not reached measurement stage."),
      paybackMonths: unavailable("Depends on final benefit model."),
      assumptions: "Draft model under review with Metrology and Finance.",
    },
    risks: [
      {
        id: "R-01",
        title: "Legacy tool drivers may not expose required telemetry",
        severity: "High",
        probability: 4,
        impact: 4,
        owner: "Kenji Watanabe",
        mitigation: "Driver capability audit scheduled before design freeze.",
        mitigationStatus: "Not started",
      },
    ],
    issues: [],
    milestones: [
      { id: "M1", name: "Kickoff and scope lock", plannedDate: "2026-10-10", weight: 15, complete: false },
      { id: "M2", name: "Architecture approved", plannedDate: "2026-11-21", weight: 25, complete: false },
      { id: "M3", name: "Pilot ingest live", plannedDate: "2027-01-23", weight: 30, complete: false },
      { id: "M4", name: "Full cutover", plannedDate: "2027-03-27", weight: 30, complete: false },
    ],
    benefit: {
      plannedFte: available(1.6),
      validatedFte: unavailable("Awaiting time study."),
      realizedFte: unavailable("Project not yet in measurement window."),
      plannedKwh: unavailable("No energy benefit claimed."),
      validatedKwh: unavailable("No energy benefit claimed."),
      realizedKwh: unavailable("No energy benefit claimed."),
      measurementPeriod: "Annualized, FY28",
    },
    ai: {
      activeUsers: 4,
      prompts: 62,
      citedSearches: 51,
      draftsProposed: 11,
      actionsConfirmed: 3,
      estimatedHoursSaved: 14,
    },
    progressSeries: [
      { label: "Sep", planned: 0, actual: 0 },
      { label: "Oct", planned: 10, actual: null },
      { label: "Nov", planned: 30, actual: null },
      { label: "Dec", planned: 45, actual: null },
      { label: "Jan", planned: 68, actual: null },
      { label: "Feb", planned: 85, actual: null },
    ],
  },
  {
    id: "CIP202607003",
    name: "Cleanroom Gown Room Flow Redesign",
    building: "B5",
    area: "Gown Room East",
    type: "CIP",
    lead: users[1],
    stage: "Buy-off",
    health: "On Track",
    startDate: "2026-07-06",
    targetFinishDate: "2026-09-30",
    lastUpdated: "2026-09-13T11:20:00Z",
    budget: {
      currency: "USD",
      approved: 142_000,
      committed: 138_500,
      actual: 131_900,
      forecastAtCompletion: 139_400,
    },
    roi: {
      expectedPct: available(124.0),
      realizedPct: available(118.4),
      paybackMonths: available(9),
      assumptions: "Benefit from 42s average gowning time reduction across 3 shifts.",
    },
    risks: [],
    issues: [
      {
        id: "I-03",
        title: "Signage revision pending EHS review",
        severity: "Low",
        owner: "Tomas Nowak",
        ageDays: 8,
        overdue: false,
      },
    ],
    milestones: [
      { id: "M1", name: "Time study complete", plannedDate: "2026-07-24", actualDate: "2026-07-22", weight: 25, complete: true },
      { id: "M2", name: "Layout approved", plannedDate: "2026-08-14", actualDate: "2026-08-13", weight: 25, complete: true },
      { id: "M3", name: "Implementation", plannedDate: "2026-09-11", actualDate: "2026-09-09", weight: 30, complete: true },
      { id: "M4", name: "Buy-off", plannedDate: "2026-09-29", weight: 20, complete: false },
    ],
    benefit: {
      plannedFte: available(1.2),
      validatedFte: available(1.1),
      realizedFte: available(1.0),
      plannedKwh: unavailable("No energy benefit claimed."),
      validatedKwh: unavailable("No energy benefit claimed."),
      realizedKwh: unavailable("No energy benefit claimed."),
      measurementPeriod: "Annualized, FY27",
    },
    ai: {
      activeUsers: 5,
      prompts: 88,
      citedSearches: 70,
      draftsProposed: 14,
      actionsConfirmed: 7,
      estimatedHoursSaved: 21,
    },
    progressSeries: [
      { label: "Jun", planned: 0, actual: 0 },
      { label: "Jul", planned: 22, actual: 25 },
      { label: "Aug", planned: 58, actual: 60 },
      { label: "Sep", planned: 92, actual: 90 },
      { label: "Oct", planned: 100, actual: null },
      { label: "Nov", planned: 100, actual: null },
    ],
  },
  {
    id: "PRJ202605002",
    name: "Wet Bench Chemical Delivery Interlock",
    building: "B1",
    area: "Wet Bench 3",
    type: "New Project",
    lead: users[0],
    stage: "On Hold",
    health: "On Hold",
    healthOverrideReason: "Paused pending capital re-approval in FY27 Q1 planning cycle.",
    startDate: "2026-05-11",
    targetFinishDate: "2026-12-04",
    lastUpdated: "2026-08-29T09:00:00Z",
    budget: {
      currency: "USD",
      approved: 780_000,
      committed: 240_000,
      actual: 196_000,
      forecastAtCompletion: 802_000,
    },
    roi: {
      expectedPct: available(18.9),
      realizedPct: unavailable("Project on hold."),
      paybackMonths: available(48),
      assumptions: "Primarily a safety-driven investment; ROI is secondary to risk reduction.",
    },
    risks: [
      {
        id: "R-05",
        title: "Extended hold may invalidate vendor quotation",
        severity: "High",
        probability: 4,
        impact: 3,
        owner: "Mei Tan",
        mitigation: "Request quote extension through Q1.",
        mitigationStatus: "Not started",
      },
    ],
    issues: [],
    milestones: [
      { id: "M1", name: "Safety requirements approved", plannedDate: "2026-06-19", actualDate: "2026-06-17", weight: 30, complete: true },
      { id: "M2", name: "Detailed design", plannedDate: "2026-08-28", weight: 30, complete: false },
      { id: "M3", name: "Install and SAT", plannedDate: "2026-11-27", weight: 40, complete: false },
    ],
    benefit: {
      plannedFte: unavailable("Safety-driven; no FTE benefit claimed."),
      validatedFte: unavailable("Safety-driven; no FTE benefit claimed."),
      realizedFte: unavailable("Safety-driven; no FTE benefit claimed."),
      plannedKwh: unavailable("No energy benefit claimed."),
      validatedKwh: unavailable("No energy benefit claimed."),
      realizedKwh: unavailable("No energy benefit claimed."),
      measurementPeriod: "—",
    },
    ai: {
      activeUsers: 2,
      prompts: 24,
      citedSearches: 19,
      draftsProposed: 4,
      actionsConfirmed: 1,
      estimatedHoursSaved: 5,
    },
    progressSeries: [
      { label: "Jun", planned: 18, actual: 20 },
      { label: "Jul", planned: 34, actual: 31 },
      { label: "Aug", planned: 52, actual: 33 },
      { label: "Sep", planned: 68, actual: 33 },
      { label: "Oct", planned: 84, actual: null },
      { label: "Nov", planned: 96, actual: null },
    ],
  },
  {
    id: "CIP202604001",
    name: "Preventive Maintenance Scheduling Bot",
    building: "B2",
    area: "Fab-wide",
    type: "CIP",
    lead: users[1],
    stage: "Closed",
    health: "On Track",
    startDate: "2026-04-06",
    targetFinishDate: "2026-08-28",
    lastUpdated: "2026-08-30T16:45:00Z",
    budget: {
      currency: "USD",
      approved: 96_000,
      committed: 94_000,
      actual: 91_300,
      forecastAtCompletion: 91_300,
    },
    roi: {
      expectedPct: available(210.0),
      realizedPct: available(187.5),
      paybackMonths: available(6),
      assumptions: "Benefit from eliminating manual PM scheduling across 4 areas.",
    },
    risks: [],
    issues: [],
    milestones: [
      { id: "M1", name: "Pilot live", plannedDate: "2026-06-12", actualDate: "2026-06-10", weight: 40, complete: true },
      { id: "M2", name: "Fab-wide rollout", plannedDate: "2026-08-07", actualDate: "2026-08-05", weight: 40, complete: true },
      { id: "M3", name: "Closure and handover", plannedDate: "2026-08-28", actualDate: "2026-08-27", weight: 20, complete: true },
    ],
    benefit: {
      plannedFte: available(2.0),
      validatedFte: available(1.9),
      realizedFte: available(1.9),
      plannedKwh: unavailable("No energy benefit claimed."),
      validatedKwh: unavailable("No energy benefit claimed."),
      realizedKwh: unavailable("No energy benefit claimed."),
      measurementPeriod: "Annualized, FY27",
    },
    ai: {
      activeUsers: 11,
      prompts: 302,
      citedSearches: 240,
      draftsProposed: 44,
      actionsConfirmed: 26,
      estimatedHoursSaved: 96,
    },
    progressSeries: [
      { label: "Apr", planned: 6, actual: 8 },
      { label: "May", planned: 28, actual: 30 },
      { label: "Jun", planned: 52, actual: 55 },
      { label: "Jul", planned: 78, actual: 80 },
      { label: "Aug", planned: 100, actual: 100 },
      { label: "Sep", planned: 100, actual: 100 },
    ],
  },
];

export const knowledge: KnowledgeItem[] = [
  {
    id: "K-1042",
    title: "AMHS Stocker Commissioning SOP",
    category: "SOP",
    summary:
      "Step-by-step commissioning sequence for overhead stocker units including safety interlock verification.",
    owner: "Sofia Lindqvist",
    projectId: "PRJ202609001",
    building: "B2",
    revision: "Rev 4",
    state: "Approved",
    effectiveDate: "2026-06-02",
    reviewDate: "2027-06-02",
    tags: ["AMHS", "stocker", "commissioning"],
  },
  {
    id: "K-0987",
    title: "Lessons Learned — B3 Stocker Rail Alignment Failure",
    category: "Lessons Learned",
    summary:
      "Root cause of 3-week delay on the 2025 B3 retrofit: rail segments shipped outside flatness tolerance and were not inspected at receiving.",
    owner: "Mei Tan",
    building: "B3",
    revision: "Rev 2",
    state: "Approved",
    effectiveDate: "2026-01-19",
    reviewDate: "2027-01-19",
    tags: ["AMHS", "rail", "vendor quality", "receiving inspection"],
  },
  {
    id: "K-1120",
    title: "FAT Checklist — Material Handling Systems",
    category: "FAT",
    summary: "Standard factory acceptance test checklist covering throughput, safety, and MES integration.",
    owner: "Arun Prakash",
    revision: "Rev 7",
    state: "Approved",
    effectiveDate: "2026-08-11",
    reviewDate: "2027-08-11",
    tags: ["FAT", "checklist", "MES"],
  },
  {
    id: "K-1188",
    title: "Etch Clean Cycle Optimization — BKM",
    category: "BKM",
    summary: "Best known method for reducing chamber clean cycle time without impacting particle performance.",
    owner: "Arun Prakash",
    projectId: "CIP202609002",
    building: "B1",
    revision: "Rev 1",
    state: "In Review",
    effectiveDate: "2026-09-10",
    reviewDate: "2027-09-10",
    tags: ["etch", "clean cycle", "recipe"],
  },
  {
    id: "K-1201",
    title: "Daifuku Electrical Schematics — Bay 4 Package",
    category: "Vendor Documents",
    summary: "Vendor-supplied electrical drawings for the Bay 4 stocker retrofit package.",
    owner: "Mei Tan",
    projectId: "PRJ202609001",
    building: "B2",
    revision: "Rev A",
    state: "Draft",
    effectiveDate: "2026-09-12",
    reviewDate: "2026-12-12",
    tags: ["vendor", "electrical", "schematics"],
  },
  {
    id: "K-0854",
    title: "Buy-off Package Template",
    category: "Buy-off",
    summary: "Standard buy-off evidence package structure with sign-off matrix and punch list format.",
    owner: "Dana Reyes",
    revision: "Rev 3",
    state: "Approved",
    effectiveDate: "2026-03-30",
    reviewDate: "2027-03-30",
    tags: ["buy-off", "template", "sign-off"],
  },
];

export const agentThread: AgentMessage[] = [
  {
    id: "m1",
    author: "user",
    text: "What is putting the Bay 4 stocker retrofit at risk, and has this happened before?",
  },
  {
    id: "m2",
    author: "agent",
    text:
      "Two items drive the At Risk health on PRJ202609001. R-04 (critical) — the controller firmware revision has not been validated against fab MES, with the validation window still unscheduled. I-15 (high, 11 days old, overdue) — the vendor has not supplied updated electrical schematics, which blocks the FAT checklist section 3.\n\nThis pattern has precedent: the 2025 B3 retrofit lost three weeks to rail segments that shipped outside flatness tolerance and were not caught at receiving. The lesson recommends a receiving inspection gate before install, which is not currently in the Bay 4 milestone plan.",
    citations: [
      { knowledgeId: "K-0987", title: "Lessons Learned — B3 Stocker Rail Alignment Failure", revision: "Rev 2", effectiveDate: "2026-01-19" },
      { knowledgeId: "K-1120", title: "FAT Checklist — Material Handling Systems", revision: "Rev 7", effectiveDate: "2026-08-11" },
    ],
  },
  {
    id: "m3",
    author: "user",
    text: "Add a receiving inspection milestone before site install.",
  },
  {
    id: "m4",
    author: "agent",
    text:
      "I can add that milestone. Review the change below and confirm — I will not write anything until you approve.",
    proposedAction: {
      summary: "Add milestone “Receiving inspection — rail segments” to PRJ202609001",
      changes: [
        { field: "Milestone name", from: "—", to: "Receiving inspection — rail segments" },
        { field: "Planned date", from: "—", to: "2026-11-11" },
        { field: "Weight", from: "—", to: "5 (M4 reduced 25 → 20)" },
        { field: "Owner", from: "—", to: "Tomas Nowak" },
      ],
    },
  },
];
